/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestImport } from './routes/test'
import { Route as RegisterImport } from './routes/register'
import { Route as ProfileImport } from './routes/profile'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as TicketsIndexImport } from './routes/tickets.index'
import { Route as TicketsCreateImport } from './routes/tickets.create'
import { Route as TicketsTicketIdImport } from './routes/tickets.$ticketId'
import { Route as ProjectsCreateImport } from './routes/projects.create'
import { Route as TicketsTicketIdEditImport } from './routes/tickets_.$ticketId.edit'
import { Route as ProjectsProjectIdEditImport } from './routes/projects_.$projectId.edit'

// Create/Update Routes

const TestRoute = TestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TicketsIndexRoute = TicketsIndexImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRoute,
} as any)

const TicketsCreateRoute = TicketsCreateImport.update({
  id: '/tickets/create',
  path: '/tickets/create',
  getParentRoute: () => rootRoute,
} as any)

const TicketsTicketIdRoute = TicketsTicketIdImport.update({
  id: '/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsCreateRoute = ProjectsCreateImport.update({
  id: '/projects/create',
  path: '/projects/create',
  getParentRoute: () => rootRoute,
} as any)

const TicketsTicketIdEditRoute = TicketsTicketIdEditImport.update({
  id: '/tickets_/$ticketId/edit',
  path: '/tickets/$ticketId/edit',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectIdEditRoute = ProjectsProjectIdEditImport.update({
  id: '/projects_/$projectId/edit',
  path: '/projects/$projectId/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
    '/projects/create': {
      id: '/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof ProjectsCreateImport
      parentRoute: typeof rootRoute
    }
    '/tickets/$ticketId': {
      id: '/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof TicketsTicketIdImport
      parentRoute: typeof rootRoute
    }
    '/tickets/create': {
      id: '/tickets/create'
      path: '/tickets/create'
      fullPath: '/tickets/create'
      preLoaderRoute: typeof TicketsCreateImport
      parentRoute: typeof rootRoute
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects_/$projectId/edit': {
      id: '/projects_/$projectId/edit'
      path: '/projects/$projectId/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof ProjectsProjectIdEditImport
      parentRoute: typeof rootRoute
    }
    '/tickets_/$ticketId/edit': {
      id: '/tickets_/$ticketId/edit'
      path: '/tickets/$ticketId/edit'
      fullPath: '/tickets/$ticketId/edit'
      preLoaderRoute: typeof TicketsTicketIdEditImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/test': typeof TestRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/tickets/create': typeof TicketsCreateRoute
  '/tickets': typeof TicketsIndexRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/tickets/$ticketId/edit': typeof TicketsTicketIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/test': typeof TestRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/tickets/create': typeof TicketsCreateRoute
  '/tickets': typeof TicketsIndexRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/tickets/$ticketId/edit': typeof TicketsTicketIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/test': typeof TestRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/tickets/create': typeof TicketsCreateRoute
  '/tickets/': typeof TicketsIndexRoute
  '/projects_/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/tickets_/$ticketId/edit': typeof TicketsTicketIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/test'
    | '/projects/create'
    | '/tickets/$ticketId'
    | '/tickets/create'
    | '/tickets'
    | '/projects/$projectId/edit'
    | '/tickets/$ticketId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/test'
    | '/projects/create'
    | '/tickets/$ticketId'
    | '/tickets/create'
    | '/tickets'
    | '/projects/$projectId/edit'
    | '/tickets/$ticketId/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/test'
    | '/projects/create'
    | '/tickets/$ticketId'
    | '/tickets/create'
    | '/tickets/'
    | '/projects_/$projectId/edit'
    | '/tickets_/$ticketId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  TestRoute: typeof TestRoute
  ProjectsCreateRoute: typeof ProjectsCreateRoute
  TicketsTicketIdRoute: typeof TicketsTicketIdRoute
  TicketsCreateRoute: typeof TicketsCreateRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
  ProjectsProjectIdEditRoute: typeof ProjectsProjectIdEditRoute
  TicketsTicketIdEditRoute: typeof TicketsTicketIdEditRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  TestRoute: TestRoute,
  ProjectsCreateRoute: ProjectsCreateRoute,
  TicketsTicketIdRoute: TicketsTicketIdRoute,
  TicketsCreateRoute: TicketsCreateRoute,
  TicketsIndexRoute: TicketsIndexRoute,
  ProjectsProjectIdEditRoute: ProjectsProjectIdEditRoute,
  TicketsTicketIdEditRoute: TicketsTicketIdEditRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/profile",
        "/register",
        "/test",
        "/projects/create",
        "/tickets/$ticketId",
        "/tickets/create",
        "/tickets/",
        "/projects_/$projectId/edit",
        "/tickets_/$ticketId/edit"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/test": {
      "filePath": "test.tsx"
    },
    "/projects/create": {
      "filePath": "projects.create.tsx"
    },
    "/tickets/$ticketId": {
      "filePath": "tickets.$ticketId.tsx"
    },
    "/tickets/create": {
      "filePath": "tickets.create.tsx"
    },
    "/tickets/": {
      "filePath": "tickets.index.tsx"
    },
    "/projects_/$projectId/edit": {
      "filePath": "projects_.$projectId.edit.tsx"
    },
    "/tickets_/$ticketId/edit": {
      "filePath": "tickets_.$ticketId.edit.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
